module.exports.gomeCartNative ={
     "apiData":"G:/gome-gfe/cart-node/cart",
    "statics": [
        "G:/gome-gfe/cart-node/cart",
        "D:/WORK_CART/uat"
    ],
    "project": {
        "routes": [
            [
                "/help",
                "{cwd}/help/help.html"
            ],[
                "/readme",
                "{config.apiData}/README.html"
            ],[
                "/icon",
                "{config.statics.0}/js/html/icons/index.html"
            ],[
                "/:site/api/:class/:method",
                "{config.apiData}/data/{params.site}/{params.class}/{params.method}.json"
            ],[
                "/:site/api/:init",
                "{config.apiData}/data/{params.site}/{params.init}.json"
            ]
        ],
        "tplTofn":{
            "src":"{config.statics.0}/js/template",
            "dist":"{config.statics.0}/js/templatefn",
            "/comp.js":[
                "/comp"
            ],
            "/cart.js":[
                "/cart",
                "/comp/alert",
                "/comp/gcity"
            ],
            "/shopping.js":[
                "/shopping",
                "/comp"
            ],
            "/order-success.js":[
                "/order-success"
                ,"/comp/alert"
            ],
            "/addsuccess2.js":[
                "/addsuccess2",
                "/comp/alert"
            ],
            "/payment-success.js":[
                "/payment-success"
                ,"/comp/alert"
            ],
            "/jixin.js":[
                "/jixin",
                "/comp/alert"
            ],
            "/orderModify.js":[
                "/orderModify"
            ]

        },
        "sprite":{
            "src":"{config.statics.0}/css/i/sprite",
            "dist":"{config.statics.0}/css/i/sprite.png",
            "selector":".c-i",
             "html":"{config.statics.0}/js/html/icons/index.html",
            "css":"{config.statics.0}/css/i/sprite.css"
        }
    }
}
