var GTPL={}
$.extend({
	encode: function( text ) {
		return ("" + text).split("<").join("&lt;").split(">").join("&gt;").split('"').join("&#34;").split("'").join("&#39;");
	}
})

GTPL.orderType=function(data){ var $fn=function (jQuery,$item
/**/) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<span class="status c-i order_success"></span><h3>  ');if((typeof(paymentInfos[pme])!=='undefined' && (paymentInfos[pme])!=null) && (typeof(paymentInfos[pme])==='function'?(paymentInfos[pme]).call($item):(paymentInfos[pme]))){__.push('   ');if(typeof(paymentInfos[pme].title)!=='undefined' && (paymentInfos[pme].title)!=null){__.push($.encode((typeof(paymentInfos[pme].title)==='function'?(paymentInfos[pme].title).call($item):(paymentInfos[pme].title))));}__.push('  ');}__.push('</h3>  <h4>  ');if((typeof(paymentInfos[pme])!=='undefined' && (paymentInfos[pme])!=null) && (typeof(paymentInfos[pme])==='function'?(paymentInfos[pme]).call($item):(paymentInfos[pme]))){__.push('   ');if(typeof(paymentInfos[pme].type)!=='undefined' && (paymentInfos[pme].type)!=null){__.push($.encode((typeof(paymentInfos[pme].type)==='function'?(paymentInfos[pme].type).call($item):(paymentInfos[pme].type))));}__.push('  ');}__.push('  （');if(typeof(itemTypeNum)!=='undefined' && (itemTypeNum)!=null){__.push($.encode((typeof(itemTypeNum)==='function'?(itemTypeNum).call($item):(itemTypeNum))));}__.push('种商品共 ');if(typeof(itemNum)!=='undefined' && (itemNum)!=null){__.push($.encode((typeof(itemNum)==='function'?(itemNum).call($item):(itemNum))));}__.push('件）： <b class="oc_red">¥ ');if(typeof(payAmount.toFixed)!=='undefined' && (payAmount.toFixed)!=null){__.push($.encode(payAmount.toFixed(2)));}__.push('</b></h4>');}return __;
};return $fn($,{data:data||{}}).join('')};

GTPL.pay_inBank=function(data){ var $fn=function (jQuery,$item
/**/) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<div class="oc_cashInBank">      <dl class="oc_cashInBank-attention">          <dt><b>注意事项：</b></dt>          <dd>1.请您在柜台存款时将订单编号、公司名称填写到<b class="oc_red">汇款用途</b>中。</dd>          <dd>2.请您在<b class="oc_red">');if(typeof(paymentDeadline)!=='undefined' && (paymentDeadline)!=null){__.push($.encode((typeof(paymentDeadline)==='function'?(paymentDeadline).call($item):(paymentDeadline))));}__.push('内</b>完成付款，过时我们将取消您的订单。</dd>          <dd>3.请您汇款后务必到“会员中心-我的订单”中填写<span class="oc_blue">付款确认信息</span>，否则您的订单会被取消。<br>您需要将款项转入以下账户信息：</dd>      </dl>      <table class="oc_cashInBank-info">          <tr>              <td>户名</td>              <td width="175">账号</td>              <td>开户行</td>          </tr>          <tr>              <td>国美在线电子商务有限公司</td>              <td>1100 1013 9000 5302 3958</td>              <td>中国建设银行北京铁道专业支行营业部</td>          </tr>      </table>  </div>');}return __;
};return $fn($,{data:data||{}}).join('')};

GTPL.pay_inPostOffice=function(data){ var $fn=function (jQuery,$item
/**/) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<div class="oc_cashInPost">      <dl class="oc_cashInPost-attention">          <dt><b>注意事项：</b></dt>          <dd>1.请您务必在汇款单的<b class="oc_red">附言处</b>注明订单编号和收货人信息。</dd>          <dd>2.请您在<b class="oc_red">');if(typeof(paymentDeadline)!=='undefined' && (paymentDeadline)!=null){__.push($.encode((typeof(paymentDeadline)==='function'?(paymentDeadline).call($item):(paymentDeadline))));}__.push('内</b>完成汇款，过时我们将取消您的订单。</dd>          <dd>3.请您汇款后务必到“会员中心-我的订单”中填写<a href="//myhome.gome.com.cn/member/myOrder" class="oc_blue">付款确认信息</a>，否则您的订单会被取消。<br>您需要将款项转入以下账户信息（<a href="//help.gome.com.cn/article/236-0-0.html" class="oc_blue">邮局汇款单填写说明</a>）：</dd>      </dl>      <table class="oc_cashInPost-info">          <tr>              <td>收款人</td>              <td width="175">商户号</td>          </tr>          <tr>              <td>国美在线电子商务有限公司</td>              <td>403100001945</td>          </tr>      </table>  </div>');}return __;
};return $fn($,{data:data||{}}).join('')};

GTPL.pay_inStore=function(data){ var $fn=function (jQuery,$item
/**/) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<div class="oc_cashInStore">      <p>门店地址：');if(typeof(address)!=='undefined' && (address)!=null){__.push($.encode((typeof(address)==='function'?(address).call($item):(address))));}__.push('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;电话：');if(typeof(phoneNumber)!=='undefined' && (phoneNumber)!=null){__.push($.encode((typeof(phoneNumber)==='function'?(phoneNumber).call($item):(phoneNumber))));}__.push(' </p>      <p>请您在<b class="oc_red">');if(typeof(paymentDeadline)!=='undefined' && (paymentDeadline)!=null){__.push($.encode((typeof(paymentDeadline)==='function'?(paymentDeadline).call($item):(paymentDeadline))));}__.push('内</b>完成付款，过时我们将取消您的订单</p>  </div>');}return __;
};return $fn($,{data:data||{}}).join('')};

GTPL.pay_onLine=function(data){ var $fn=function (jQuery,$item
/**/) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<div class="oc_cashOnDelivery">      ');if(typeof(sc)!=='undefined' && (sc)!=null){$.each((typeof(sc)==='function'?(sc).call($item):(sc)),function($index, $value){with(this){__.push('      <dl class="delivery">          <dt>');if(typeof(sme)!=='undefined' && (sme)!=null){__.push($.encode((typeof(sme)==='function'?(sme).call($item):(sme))));}__.push('</dt>          ');if(typeof(scs)!=='undefined' && (scs)!=null){$.each((typeof(scs)==='function'?(scs).call($item):(scs)),function($index, $value){with(this){__.push('          <dd>              <span class="i-block col_105">');if(typeof(itemTypeNum)!=='undefined' && (itemTypeNum)!=null){__.push($.encode((typeof(itemTypeNum)==='function'?(itemTypeNum).call($item):(itemTypeNum))));}__.push('种商品共');if(typeof(itemNum)!=='undefined' && (itemNum)!=null){__.push($.encode((typeof(itemNum)==='function'?(itemNum).call($item):(itemNum))));}__.push('件</span>              ');if((typeof(shippingDateAsString)!=='undefined' && (shippingDateAsString)!=null) && (typeof(shippingDateAsString)==='function'?(shippingDateAsString).call($item):(shippingDateAsString))){__.push('<span class="i-block col_300">送货时间：');if(typeof(shippingDateAsString)!=='undefined' && (shippingDateAsString)!=null){__.push($.encode((typeof(shippingDateAsString)==='function'?(shippingDateAsString).call($item):(shippingDateAsString))));}__.push('</span>');}__.push('          </dd>          ');}});}__.push('      </dl>      ');}});}__.push('  </div>');}return __;
};return $fn($,{data:data||{}}).join('')};

GTPL.rebateInfos=function(data){ var $fn=function (jQuery,$item
/**/) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<dt>您的订单包含如下赠券和积分赠送，每个订单在完成确认收货后将直接发放到您的个人账户上：</dt>  <dd>消费积分：');if(typeof(points)!=='undefined' && (points)!=null){__.push($.encode((typeof(points)==='function'?(points).call($item):(points))));}__.push('分</dd>  ');if((typeof(cVOs.length > 0)!=='undefined' && (cVOs.length > 0)!=null) && (typeof(cVOs.length > 0)==='function'?(cVOs.length > 0).call($item):(cVOs.length > 0))){__.push('  ');if(typeof(cVOs)!=='undefined' && (cVOs)!=null){$.each((typeof(cVOs)==='function'?(cVOs).call($item):(cVOs)),function($index, $value){with(this){__.push('  <dd>');if(typeof(coupons[couponType])!=='undefined' && (coupons[couponType])!=null){__.push($.encode((typeof(coupons[couponType])==='function'?(coupons[couponType]).call($item):(coupons[couponType]))));}__.push('：');if(typeof(quantity)!=='undefined' && (quantity)!=null){__.push($.encode((typeof(quantity)==='function'?(quantity).call($item):(quantity))));}__.push('张</dd>  ');}});}__.push('  ');}__.push('');}return __;
};return $fn($,{data:data||{}}).join('')};

GTPL.comp_alert=function(data){ var $fn=function (jQuery,$item
/**/) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<div class="g-panel box-sd2">   ');if((typeof(close)!=='undefined' && (close)!=null) && (typeof(close)==='function'?(close).call($item):(close))){__.push('   <i class="c-i closebtn-new fr" g-panel-close></i>   ');}__.push('   <div class="body">    <div class="icon i-block">     <i class="c-i panel-');if(typeof(type)!=='undefined' && (type)!=null){__.push($.encode((typeof(type)==='function'?(type).call($item):(type))));}__.push('"></i>    </div>    <div class="content i-block">     ');if(typeof(body)!=='undefined' && (body)!=null){__.push((typeof(body)==='function'?(body).call($item):(body)));}__.push('    </div>    ');if((typeof($data.code)!=='undefined' && ($data.code)!=null) && (typeof($data.code)==='function'?($data.code).call($item):($data.code))){__.push('         <div class="errorCode">[');if(typeof($data.code)!=='undefined' && ($data.code)!=null){__.push($.encode((typeof($data.code)==='function'?($data.code).call($item):($data.code))));}__.push(']</div>    ');}__.push('    <div class="i-block" style="vertical-align: middle;width:1px;min-height:1px;"></div>   </div>  </div>');}return __;
};return $fn($,{data:data||{}}).join('')};

GTPL.comp_alertWar=function(data){ var $fn=function (jQuery,$item
/**/) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<div class="g-panel box-sd2">   ');if((typeof(close)!=='undefined' && (close)!=null) && (typeof(close)==='function'?(close).call($item):(close))){__.push('   <i class="c-i closebtn-new fr" g-panel-close></i>   ');}__.push('   <div class="body">    <div class="icon i-block" style="vertical-align: top;">     <i class="c-i panel-');if(typeof(type)!=='undefined' && (type)!=null){__.push($.encode((typeof(type)==='function'?(type).call($item):(type))));}__.push('"></i>    </div>    <div class="content i-block">     ');if(typeof(body)!=='undefined' && (body)!=null){__.push((typeof(body)==='function'?(body).call($item):(body)));}__.push('    </div>    ');if((typeof($data.code)!=='undefined' && ($data.code)!=null) && (typeof($data.code)==='function'?($data.code).call($item):($data.code))){__.push('         <div class="errorCode">[');if(typeof($data.code)!=='undefined' && ($data.code)!=null){__.push($.encode((typeof($data.code)==='function'?($data.code).call($item):($data.code))));}__.push(']</div>    ');}__.push('    <div class="i-block" style="vertical-align: middle;width:1px;min-height:1px;"></div>   </div>  </div>');}return __;
};return $fn($,{data:data||{}}).join('')};

GTPL.comp_biz001=function(data){ var $fn=function (jQuery,$item
/**/) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<div class="g-panel box-sd2 gpanel-biz001">   <div class="body">    <div class="icon i-block">     <i class="c-i order_waring"></i>    </div>    <div class="content i-block">     <h4>所有说您订单异常要退款的都是大骗子！！！</h4>     <p>当有人以订单异常为由通知您需要退款，就算他有您的各类相关信息，无论他是以电话、短信、QQ、微信、邮件等任何形式通知您，他都是骗子、骗子、大骗子......</p>     <div class="btns">      <a      g-panel-close      href="javascript:void(0)"       class="btn btn-disabled">       知道了，我不会理骗子的！      </a>     </div>    </div>        <div class="foolter">     <b>特别提醒！！！</b>国美不会通过电话、短信、QQ、微信、邮件等各类形式以订单异常为由通知您需要退款。此类行为均为诈骗！请认准官方电话 4008-708-708（或010-58851777）    </div>   </div>  </div>');}return __;
};return $fn($,{data:data||{}}).join('')};

GTPL.comp_confirm=function(data){ var $fn=function (jQuery,$item
/**/) {
var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('<div class="g-panel box-sd2 confirm">   ');if((typeof(util.is)!=='undefined' && (util.is)!=null) && util.is(Function,close)){__.push('    <i class="c-i closebtn-new fr" g-panel-close></i>   ');}__.push('   <div class="body">    ');if((typeof(util.is)!=='undefined' && (util.is)!=null) && util.is(Function,body)){__.push('     ');if(typeof(body)!=='undefined' && (body)!=null){__.push((body).call($item));}__.push('    ');}else if((true) && true){__.push('    <div class="icon i-block">     <i class="c-i panel-');if(typeof(type)!=='undefined' && (type)!=null){__.push((typeof(type)==='function'?(type).call($item):(type)));}__.push('"></i>    </div>    <div class="content i-block">     ');if((typeof(title)!=='undefined' && (title)!=null) && (typeof(title)==='function'?(title).call($item):(title))){__.push('     <h1>');if(typeof(title)!=='undefined' && (title)!=null){__.push((typeof(title)==='function'?(title).call($item):(title)));}__.push('</h1>     ');}__.push('     ');if(typeof(body)!=='undefined' && (body)!=null){__.push((typeof(body)==='function'?(body).call($item):(body)));}__.push('    </div>    <div class="i-block" style="vertical-align: middle;width:1px;min-height:1px;"></div>    ');}__.push('   </div>   ');if((typeof(btns.length>0)!=='undefined' && (btns.length>0)!=null) && (typeof(btns.length>0)==='function'?(btns.length>0).call($item):(btns.length>0))){__.push('   <div class="btns">    ');if(typeof(btns)!=='undefined' && (btns)!=null){$.each((typeof(btns)==='function'?(btns).call($item):(btns)),function($index, $value){with(this){__.push('     <a     g-btn-path="btns,');if(typeof($index)!=='undefined' && ($index)!=null){__.push($.encode((typeof($index)==='function'?($index).call($item):($index))));}__.push('"      href="javascript:void(0)"      class="');if(typeof(clazz)!=='undefined' && (clazz)!=null){__.push($.encode((typeof(clazz)==='function'?(clazz).call($item):(clazz))));}__.push('">      ');if(typeof(btnName)!=='undefined' && (btnName)!=null){__.push((typeof(btnName)==='function'?(btnName).call($item):(btnName)));}__.push('     </a>    ');}});}__.push('   </div>   ');}__.push('  </div>');}return __;
};return $fn($,{data:data||{}}).join('')};